#!/usr/bin/env bash

set -o allexport

ENV_FILE="${ENV_FILE:-.env}"

if [[ -r $ENV_FILE ]]; then
    # shellcheck disable=SC1090
    source "$ENV_FILE"
else
    printf "\033[93m%s\033[0m\n" "Warning: Cannot read from \"$ENV_FILE\". Make sure the file path is correct & has required permissions." >&2
fi

GO_VERSION=$(go list -m -f "{{.GoVersion}}")
PACKAGE_NAME=$(go list -m)
APP_NAME=${PACKAGE_NAME##*/}
APP_VERSION=$(git describe --tags --always --dirty)
DOCKERHUB_REPO_NAME=$(echo "$PACKAGE_NAME" | awk -F'/' '{print $2 "/" $3}')

set +o allexport

set -e

build_debug_args=(--ldflags="-X $PACKAGE_NAME/internal/config.BuildInfo=$APP_NAME::$APP_VERSION::debug" --race)
build_release_args=(--ldflags="-s -w -X $PACKAGE_NAME/internal/config.BuildInfo=$APP_NAME::$APP_VERSION::release -extldflags=-static" --trimpath --buildmode=pie)

task=$1

while true; do
    case $task in
    "docker-watch")
        compose_file="docker-compose.yml"
        docker compose -f "$compose_file" down --remove-orphans
        docker compose -f "$compose_file" up --build
        break
        ;;
    "docker-build")
        docker build --tag="$APP_NAME":"$APP_VERSION" --target="prod" --build-arg="GO_VERSION=$GO_VERSION" .
        break
        ;;
    "docker-push")
        docker login
        docker tag "$APP_NAME":"$APP_VERSION" "$DOCKERHUB_REPO_NAME":"$APP_VERSION"
        docker push "$DOCKERHUB_REPO_NAME":"$APP_VERSION"
        break
        ;;
    "watch")
        watchexec --stop-timeout="${SHUTDOWN_TIMEOUT:-10s}" --stop-signal=SIGINT --shell=none --restart ./tasks run
        break
        ;;
    "run")
        CGO_ENABLED=0 go run "${build_debug_args[@]}" .
        break
        ;;
    "start")
        if [[ -x "./bin/build" ]]; then
            ./bin/"build"
        else
            echo "Build not found. Building..." && sleep 1 && ./tasks build && ./bin/build
        fi
        break
        ;;
    "build")
        echo "building app..." && CGO_ENABLED=0 go build "${build_release_args[@]}" -o ./bin/build ./main.go && echo "built app successfully ✔"
        break
        ;;
    "test")
        go test --race --count=2 -v ./...
        break
        ;;
    "test-cover")
        go test --race --coverprofile=./tmp/coverage.out ./... && go tool cover --html=./tmp/coverage.out
        break
        ;;
    "bench")
        go test --race --count=2 -v -benchmem --bench=. ./...
        break
        ;;
    "checkpoint")
        git add . && git commit -m "Checkpoint at $(date "+%Y-%m-%dT%H:%M:%S%z")" && git push && echo "Checkpoint created and pushed to remote ✔"
        break
        ;;
    *)
        menu="
 1) docker-watch    -  Run development server in docker
 2) docker-build    -  Build docker image
 3) docker-push     -  Push docker image to dockerhub
 4) watch           -  Run go app and watch for changes
 5) run             -  Run go app without building (for development)
 6) start           -  Run go app build
 7) build           -  Build go app (for release)
 8) test            -  Run tests
 9) test-cover      -  Run tests and show coverage
10) bench           -  Run benchmarks
11) checkpoint      -  Create a git checkpoint and push to remote"
        printf "\033[95m%s\033[0m%s\n%s\n" "Available tasks" "$menu" "Usage: $0 <task>"
        break
        ;;
    esac
done
